In [3]:
import numpy as np
import pandas as pd

# ALL DATASET
data = pd.read_csv('data_fs.dat', delim_whitespace=True, decimal=",")
data = data[data["y"]>0]
data

,id,x,y,z,fwhm_x,fwhm_y,e,tilt,co_max,cx_max,xpd,sub_spill,main_spill
0,21,-0.316965,0.326756,50,0.398546,0.365183,1.091361,131.516741,53.84,13.10,40.74,0.001675,0.005413
1,42,-0.318192,0.272044,50,0.364137,0.398634,1.094738,36.860917,53.86,12.79,41.07,0.001237,0.004431
2,63,-0.319138,0.217441,50,0.364608,0.396464,1.087371,31.285228,53.88,12.11,41.77,0.000910,0.004168
3,83,-0.320197,0.163140,45,0.361428,0.384678,1.064326,22.716133,54.07,12.21,41.85,0.000715,0.003629
4,103,-0.321053,0.108822,40,0.358714,0.376443,1.049424,17.159739,54.20,11.60,42.60,0.000600,0.003919
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,3318,0.333326,0.271998,50,0.350770,0.401112,1.143520,-26.751477,53.99,13.38,40.61,0.000798,0.010065
158,3339,0.331717,0.217468,50,0.351115,0.398046,1.133661,-22.414060,54.02,12.87,41.15,0.000577,0.010663
159,3360,0.330462,0.163029,50,0.351985,0.395278,1.122996,-17.597785,54.04,13.01,41.03,0.000430,0.010768
160,3380,0.329983,0.108774,45,0.351460,0.385294,1.096266,-12.457245,54.17,12.91,41.25,0.000344,0.010594
161,3400,0.329892,0.054440,40,0.350706,0.376969,1.074886,-5.864244,54.28,12.41,41.87,0.000301,0.010913